name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read .node_version
        run: echo ::set-output name=NODE_VERSION::$(cat .node-version)
        id: node_version

      - name: Setup NodeJS
        uses: actions/setup-node@v2.1.5

      - name: Cache node modules
        uses: actions/cache@v2.1.4
        with:
          path: ~/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run test
        run: npm run test:ci
